### ISSUE TITLE
Maintenance procedures images

### ISSUE THREAD

**Issue by petebachant** [UNH-OE/wave-tow-tank#78]
Just uploading these here:

![Adjusting the belt tensioning clamp](https://cloud.githubusercontent.com/assets/4604869/12929253/be295f72-cf3f-11e5-9b43-a45ec581b5a4.png)

![Measuring tensioning clamp overlap; currently at 1 3/4"](https://cloud.githubusercontent.com/assets/4604869/12929265/c575c496-cf3f-11e5-8270-ad1b71b6d9df.png)

![Using a bar clamp to start the nuts on the tensioning clamp](https://cloud.githubusercontent.com/assets/4604869/12929272/cdee22e4-cf3f-11e5-99cc-107cbebc03c2.png)

**Comment by jcahern** [comment]
did you buy a custom roll in the past?  seems like they like to go 12, 
6, 3, 2, 1, etc.  but not 4.75 or 5" width.  have you tried to buy a 
larger roll and cut it down?

**Comment by petebachant** [comment]
Hey @jcahern, just an FYI: I have been adding replies in https://github.com/UNH-OE/wave-tow-tank/issues/70
